services:
  postgres:
    image: postgres:16
    container_name: pg-hapi
    restart: unless-stopped
    environment:
      POSTGRES_USER: hadi
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hapi
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hapi-net

volumes:
  pgdata:

networks:
  hapi-net: